import React, { useState, useRef } from 'react';
import { scanProtocol } from './services/geminiService';
import { AnalysisResult, AppState } from './types';
import { PersonCard } from './components/PersonCard';
import { ScannerEffect } from './components/ScannerEffect';
import { InfoModal } from './components/InfoModal';

// Icons
const SearchIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
    <path strokeLinecap="round" strokeLinejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
  </svg>
);

const WarningIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-12 h-12 text-neon-red mb-4">
      <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" />
    </svg>
);

const DownloadIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
    <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
  </svg>
);

const InfoIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
    <path strokeLinecap="round" strokeLinejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
  </svg>
);

const App: React.FC = () => {
  const [query, setQuery] = useState('');
  const [state, setState] = useState<AppState>(AppState.IDLE);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showInfo, setShowInfo] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const handleScan = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setState(AppState.SCANNING);
    setError(null);
    setResult(null);

    // Simulate a bit of UI build-up time before request
    setTimeout(async () => {
        try {
            const data = await scanProtocol(query);
            setResult(data);
            setState(AppState.SUCCESS);
        } catch (err: any) {
            console.error(err);
            setError(err.message || "Connection to neural net failed. Try again.");
            setState(AppState.ERROR);
        }
    }, 800);
  };

  const handleClear = () => {
      setQuery('');
      setState(AppState.IDLE);
      setResult(null);
      if(inputRef.current) inputRef.current.focus();
  }

  const handleExport = () => {
    if (!result) return;

    const timestamp = new Date().toLocaleString();
    const separator = "=".repeat(60);
    const thinSeparator = "-".repeat(60);
    
    let content = `CLASSIFIED INTELLIGENCE DOSSIER\n`;
    content += `GENERATED BY CULT SCANNER\n`;
    content += `TIMESTAMP: ${timestamp}\n`;
    content += `${separator}\n\n`;
    
    content += `SUBJECT PROTOCOL: ${result.protocol.toUpperCase()}\n\n`;
    content += `SUMMARY:\n${result.summary}\n\n`;
    content += `${separator}\n\n`;
    
    content += `DETECTED PROFILES (${result.profiles.length})\n\n`;
    
    result.profiles.forEach((p, i) => {
        content += `[TARGET #${String(i + 1).padStart(2, '0')}: ${p.name.toUpperCase()}]\n`;
        content += `ROLE: ${p.role}\n`;
        content += `VERDICT: ${p.verdict}\n`;
        content += `CULT SCORE: ${p.cultScore}/10\n`;
        
        if (p.socials) {
            content += `SOCIALS:\n`;
            if(p.socials.twitter) content += `  - Twitter: ${p.socials.twitter}\n`;
            if(p.socials.linkedin) content += `  - LinkedIn: ${p.socials.linkedin}\n`;
            if(p.socials.telegram) content += `  - Telegram: ${p.socials.telegram}\n`;
            if(p.socials.farcaster) content += `  - Farcaster: ${p.socials.farcaster}\n`;
        }
        
        content += `\nDIAGNOSIS:\n${p.diagnosis}\n\n`;
        content += `BACKGROUND:\n${p.background}\n\n`;
        if(p.conspiracies) {
            content += `RED FLAGS / CONSPIRACIES:\n${p.conspiracies}\n\n`;
        }
        content += `${thinSeparator}\n\n`;
    });
    
    if (result.sources.length > 0) {
        content += `INTELLIGENCE SOURCES\n\n`;
        result.sources.forEach((s, i) => {
            content += `[${i + 1}] ${s.title}\n    ${s.uri}\n\n`;
        });
    }
    
    content += `${separator}\n`;
    content += `END OF REPORT`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `CULT_DOSSIER_${result.protocol.replace(/\s+/g, '_').toUpperCase()}.txt`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen font-sans text-gray-200 relative selection:bg-neon-green selection:text-black">
      {/* Background Grid */}
      <div className="fixed inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:50px_50px] pointer-events-none -z-10"></div>
      
      {state === AppState.SCANNING && <ScannerEffect />}

      <header className="p-6 border-b border-gray-900 bg-black/50 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-6xl mx-auto flex justify-between items-center">
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 bg-neon-green rounded-full animate-pulse"></div>
            <h1 className="text-xl font-bold tracking-widest font-mono text-white">
              CULT <span className="text-neon-green">SCANNER</span>
            </h1>
          </div>
          
          <div className="flex items-center gap-6">
            <div className="text-xs font-mono text-gray-500 hidden sm:block">
                SYSTEM_STATUS: <span className="text-neon-green">ONLINE</span>
            </div>
            <button 
                onClick={() => setShowInfo(true)}
                className="flex items-center gap-2 text-xs font-mono text-gray-400 hover:text-neon-green transition-colors border border-gray-800 hover:border-neon-green px-3 py-1 rounded"
            >
                <InfoIcon />
                <span className="hidden sm:inline">SYSTEM INFO</span>
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto p-4 sm:p-6 pb-20">
        
        {/* Search Section */}
        <section className={`transition-all duration-700 ease-in-out ${state === AppState.IDLE ? 'mt-[25vh] max-w-2xl mx-auto text-center' : 'mt-6 mb-12'}`}>
           {state === AppState.IDLE && (
               <h2 className="text-4xl sm:text-5xl font-bold mb-10 glitch-text font-mono animate-fadeIn">
                   DIAGNOSE THE <br/><span className="text-neon-purple">FOUNDERS</span>
               </h2>
           )}
           
           <form onSubmit={handleScan} className="relative z-20">
             <div className="relative group">
                <input
                    ref={inputRef}
                    type="text"
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    placeholder="ENTER PROTOCOL NAME (e.g., 'Hex', 'Solana', 'SafeMoon')"
                    className="w-full bg-black/80 border border-gray-800 text-white p-4 pl-12 pr-32 rounded-lg focus:outline-none focus:border-neon-green focus:ring-1 focus:ring-neon-green/50 shadow-[0_0_0_0_rgba(0,255,65,0)] focus:shadow-[0_0_20px_rgba(0,255,65,0.1)] transition-all duration-300 font-mono text-lg placeholder:text-gray-700"
                    disabled={state === AppState.SCANNING}
                    autoFocus
                />
                <div className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-600 group-focus-within:text-neon-green transition-colors">
                    <SearchIcon />
                </div>
                <button 
                    type="submit"
                    disabled={state === AppState.SCANNING || !query}
                    className="absolute right-2 top-2 bottom-2 bg-gray-900 hover:bg-neon-green hover:text-black text-white px-6 rounded font-mono font-bold uppercase tracking-wider transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center border border-gray-800 hover:border-neon-green"
                >
                    {state === AppState.SCANNING ? (
                        <span className="flex items-center gap-2">
                            <span className="w-1.5 h-1.5 bg-current rounded-full animate-bounce"></span>
                            <span className="w-1.5 h-1.5 bg-current rounded-full animate-bounce delay-75"></span>
                            <span className="w-1.5 h-1.5 bg-current rounded-full animate-bounce delay-150"></span>
                        </span>
                    ) : 'SCAN'}
                </button>
             </div>
             
             {/* Branding Footer / Creator Link */}
             {state === AppState.IDLE && (
                 <div className="mt-16 flex flex-col items-center gap-4 animate-fadeIn opacity-0" style={{ animationFillMode: 'forwards', animationDelay: '0.3s' }}>
                     <p className="text-gray-600 text-[10px] font-mono uppercase tracking-[0.25em]">
                         Built By Crypto Alchemy
                     </p>
                     <a 
                        href="https://x.com/cryptoalchemy29" 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="group relative inline-block"
                     >
                        {/* Pulse ring */}
                        <div className="absolute -inset-2 bg-neon-green/20 rounded-full blur-md opacity-0 group-hover:opacity-100 transition duration-500 animate-pulse"></div>
                        
                        <img 
                            src="https://pbs.twimg.com/profile_images/1954480691242057728/Fg8Nrt_U_400x400.jpg" 
                            alt="Crypto Alchemy" 
                            className="w-14 h-14 rounded-full border-2 border-gray-800 group-hover:border-neon-green transition-all duration-500 object-cover relative z-10 grayscale group-hover:grayscale-0"
                        />
                     </a>
                 </div>
             )}
           </form>
        </section>

        {/* Error State */}
        {state === AppState.ERROR && (
            <div className="max-w-2xl mx-auto mt-20 text-center p-8 border border-red-900/50 bg-red-950/10 rounded-lg animate-fadeIn">
                <div className="flex justify-center"><WarningIcon /></div>
                <h3 className="text-xl font-bold text-red-500 mb-2 font-mono">SCAN FAILED</h3>
                <p className="text-gray-400 mb-6">{error}</p>
                <button onClick={handleClear} className="text-white underline underline-offset-4 hover:text-red-400 transition-colors">
                    RESET SYSTEM
                </button>
            </div>
        )}

        {/* Results */}
        {state === AppState.SUCCESS && result && (
            <div className="animate-fadeIn">
                {/* Protocol Summary Header */}
                <div className="mb-10 border-l-4 border-neon-green pl-6 py-2">
                    <h2 className="text-3xl font-bold text-white font-mono uppercase mb-2">{result.protocol}</h2>
                    <p className="text-gray-400 text-lg leading-relaxed max-w-3xl">"{result.summary}"</p>
                </div>

                {/* Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-16">
                    {result.profiles.map((profile, idx) => (
                        <PersonCard key={idx} profile={profile} />
                    ))}
                </div>

                {/* Sources Footnote */}
                {result.sources.length > 0 && (
                    <div className="border-t border-gray-800 pt-8 mt-12">
                        <h4 className="text-xs font-bold text-gray-600 uppercase tracking-widest mb-4">Intel Sources / Evidence</h4>
                        <ul className="grid grid-cols-1 md:grid-cols-2 gap-2">
                            {result.sources.map((source, idx) => (
                                <li key={idx} className="flex items-center gap-2 text-sm text-gray-500 truncate hover:text-neon-green transition-colors">
                                    <span className="text-gray-700 select-none">[{idx + 1}]</span>
                                    <a href={source.uri} target="_blank" rel="noopener noreferrer" className="truncate underline decoration-gray-800 hover:decoration-neon-green underline-offset-4">
                                        {source.title}
                                    </a>
                                </li>
                            ))}
                        </ul>
                    </div>
                )}
                
                <div className="text-center mt-20 flex flex-col sm:flex-row justify-center gap-4">
                    <button onClick={handleClear} className="px-8 py-3 border border-gray-800 text-gray-500 hover:border-white hover:text-white transition-all rounded font-mono uppercase text-sm tracking-widest">
                        Run New Scan
                    </button>
                    <button onClick={handleExport} className="px-8 py-3 bg-gray-900 hover:bg-neon-green hover:text-black text-neon-green border border-neon-green/50 transition-all rounded font-mono uppercase text-sm tracking-widest flex items-center justify-center gap-2 group">
                        <DownloadIcon />
                        <span>Export Dossier</span>
                    </button>
                </div>
            </div>
        )}

        {/* Modal */}
        {showInfo && <InfoModal onClose={() => setShowInfo(false)} />}

      </main>
    </div>
  );
};

export default App;